(define (pascals-triangle row column)
    (cond ((= row 0) 1)
          ((= column 0) 1)
          ((= row column) 1)
          (else (+ (pascals-triangle (- row 1) (- column 1))
             (pascals-triangle (- row 1) column)
          ))
    )
)
